config/routes.rb
Rails.application.routes.draw do
  # require 'sidekiq/web'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users 
  devise_for :users, :controllers => {:registrations => "users/registrations", sessions: "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  resources :gallery	
	 		
  root 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/about_us' => 'home#about_us'
  post '/message' => 'home#message'
  post '/import_image' => 'gallery#import_image'
  get '/get_image/:id', to: 'gallery#get_image', as: 'get_image'
  get '/gallery_count', to: 'gallery#gallery_count'


  
  # mount Sidekiq::Web => '/sidekiq'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	
	#before_action :authenticate_user!	

	def about_us
		
	end

	def contact_us
		
	end

	def message
		@contact = Contact.new(contact_params)
	  respond_to do |format|
	  	if @contact.save
    		#BackgroundWorker.perform(@contact.id)
    		ContactMailer.contact_us_email(@contact).deliver
    		format.html { redirect_to contact_us_path, notice: 'Message successfully send.' }
        format.json { render json: { status: "Success", message: "Successful", code: 200 } }	
    	else
    			format.html { render :contact_us, notice: @query.errors.full_messages  }
    		 format.json { render json: { status: "Failure", message: @query.errors.full_messages, code: 500 } }
    	end 
    end	
 	end	 
		
	private
	  def contact_params
	    params.require(:contact).permit(:name, :email, :mobile_number, :description)
	  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_form.html.erb
<div class="well well-sm">
	<%= form_for :contact, url: message_path,remote: true, :html => { :id => "contact_us"}  do |f| %>
    	<div class="row">
      	<div class="col-md-6">
          	<div class="form-group">
              	<%= f.label :name %><br>
              	<%= f.text_field :name, class: "form-control" , placeholder: "Enter Name" %>
          	</div>
          	<div class="form-group">
              	<label for="email">
                  	Email Address</label>
              	<div class="input-group">
                  	<span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                  	</span>
                  	<%= f.text_field :email, class: "form-control", placeholder: "Enter Email", id: "validate" %>
                  </div>
          	</div>
          	<div class="form-group">
              	<label for="email">
                  	Mobile Number</label>
              	<div class="input-group">
                  	<%= f.text_field :mobile_number, class: "form-control", placeholder: "Enter Mobile Number" %>
                  </div>
          	</div>
          	<div class="form-group">
              	<label for="email">
                  	Message</label>
              	<div class="input-group">
                  	<%= f.text_area :description, class: "form-control", placeholder: "Leave your message here?", :style=> "resize:none"%>
                  </div>
          	</div>
      	</div>

      	<div class="col-md-12">
      		<%= f.submit "Send Message",  class: "fbtn btn-primary pull-right" %>
      	</div>
    	</div>
  <% end %>
</div>

app/views/home/about_us.html.erb
<div class="aboutus-maropost">
    <div class="slide-aboutus">
    <img src="https://www.maropost.com/wp-content/uploads/2016/10/m-landing-sun-hero-large-copy.png" alt="", style="max-width: 120%;">
    <div class="content-slide">
        <img src="https://www.maropost.com/wp-content/themes/maropost-new/web/images/img-m.png" alt="">
        <h2>ABOUT US</h2>
    </div>
</div>
<div class="we-are-maropost">
    <div class="container">
        <div class="inner-content">
            <h2>We Are Maropost</h2>
            <h6>We make the world's best marketing and sales platforms</h6>
        <div class="we-are-maropost-item">
           <p>Maropost is the leading global provider of on-demand marketing, sales, commerce, and infrastructure solutions. We offer the world’s best marketing and sales cloud platforms combined with industry leading customer support and client success.</p>
            <a href="https://www.maropost.com/leadership-team/">MEET OUR LEADERSHIP TEAM</a>
        </div>
        <div class="we-are-maropost-item">
         	<p>Maropost was founded in 2011 by CEO and Chairman Ross Andrew Paquette. We are headquartered in Toronto, Canada, with offices in New York, USA, London, U.K., and Chandigarh, India.</p>
            <a href="https://www.maropost.com/client-case-studies/">READ OUR CASE STUDIES</a>
        </div>
        <div class="we-are-maropost-item">
         	<p>Maropost is the fastest growing company in Toronto and among the fastest growing companies in North America. In 2016, Maropost was ranked 4th in Deloitte's Canadian Technology Fast 50, 7th in the annual PROFIT 500 of Canada's fastest- growing companies, and 37th in the North America-wide Deloitte Fast 500.</p>
           	<a href="http://www.maropost.com/careers-at-maropost/">CHECK OUT OUR CAREERS</a>
        </div>
    </div>
</div>
</div>
   	














<style type="text/css">
	.aboutus-maropost .we-are-maropost .inner-content {
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
    margin-top: -8px;
    background-image: linear-gradient(to top, #00e1fd 0%, #00bef8 100%);
    float: left;
    width: 100%;
    color: #fff;
    padding: 53px 70px 48px 72px;
}

.aboutus-maropost .slide-aboutus .content-slide h2 {
    text-transform: uppercase;
    font-size: 32px;
    font-weight: 400;
    line-height: 55px;
    color: #ccc;
}

.aboutus-maropost .we-are-maropost .inner-content a {
    font-size: 14px;
    text-transform: uppercase;
    color: #fff;
    background-image: linear-gradient(180deg, #8e9197 0%, #55585e 100%);
    border-radius: 8px;
    display: block;
    width: 246px;
    height: 41px;
    text-align: center;
    line-height: 41px;
    margin-top: 16px;
    letter-spacing: -0.54px;
}

.aboutus-maropost .product-family .wrapper-product-fam {
    box-shadow: 0 0 8px rgba(0, 0, 0, 0.15);
    border: 1px solid rgba(151, 151, 151, 0.25);
    float: left;
    width: 100%;
    /* padding-bottom: 34px; */
    padding-top: 8px;
}
(index):163
.aboutus-maropost .product-family .wrapper-product-fam {
    padding-top: 50px !important;
}
.aboutus-maropost .product-family .box-item .top-box {
    height: 58px;
    -webkit-border-radius: 8px 8px 0 0;
    -moz-border-radius: 8px 8px 0 0;
    -ms-border-radius: 8px 8px 0 0;
    border-radius: 8px 8px 0 0;
    background-image: linear-gradient(to top, #00e1fd 0%, #00bef8 100%);
    position: relative;
}
.aboutus-maropost .product-family .box-item .top-box {
    height: 100px !important;
}

.aboutus-maropost .product-family .box-item {
    position: relative;
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    -ms-border-radius: 8px;
    border-radius: 8px;
    min-height: 570px;
    width: 458px;
    border: 1px solid rgba(151, 151, 151, 0.25);
    -moz-box-shadow: 0 0 8px rgba(0, 0, 0, 0.44);
    -webkit-box-shadow: 0 0 8px rgba(0, 0, 0, 0.44);
    box-shadow: 0 0 8px rgba(0, 0, 0, 0.44);
    float: left;
}

.aboutus-maropost .product-family .box-item .text-box a {
    text-transform: uppercase;
    background-image: linear-gradient(180deg, #00e1fd 0%, #00bef8 100%);
    box-shadow: 0 3px 4px 1px rgba(0, 0, 0, 0.2);
    width: 246px;
    height: 41px;
    text-align: center;
    line-height: 41px;
    display: block;
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    -ms-border-radius: 8px;
    border-radius: 8px;
    margin: auto;
    color: #fff;
    position: absolute;
    left: 0;
    right: 0;
    bottom: 30px;
}

content-slide h2 {
    padding: 0px 43px 5px 406px;
}

.aboutus-maropost .slide-aboutus .content-slide h2 {
    padding: 0px 43px 5px 406px;
}

.footer-bottom {
    margin-top: 3%;
}
</style>

app/views/home/contact_us.html.erb
<div class="container">
	<div class="row">
    <div class="col-sm-12 col-lg-12">
        <h1 class="h1">
            Contact us <small>Feel free to contact us</small></h1>
    </div>
    <div class="flash"></div>
	</div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8" id="contact_form">
      <div class="well well-sm">
	    	<%= form_for :contact, url: message_path,remote: true, :html => { :id => "contact_us"}  do |f| %>
	        	<div class="row">
            	<div class="col-md-6">
                	<div class="form-group">
                    	<%= f.label :name %><br>
                    	<%= f.text_field :name, class: "form-control" , placeholder: "Enter Name" %>
                	</div>
                	<div class="form-group">
                    	<label for="email">
                        	Email Address</label>
                    	<div class="input-group">
                        	<span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                        	</span>
                        	<%= f.text_field :email, class: "form-control", placeholder: "Enter Email" %>
                        </div>
                        <div id="result"></div>
                	</div>
                	<div class="form-group">
                    	<label for="email">
                        	Mobile Number</label>
                    	<div class="input-group">
                        	<%= f.text_field :mobile_number, class: "form-control", placeholder: "Enter Mobile Number" %>
                        </div>
                	</div>
                	<div class="form-group">
                    	<label for="email">
                        	Message</label>
                    	<div class="input-group">
                        	<%= f.text_area :description, class: "form-control", placeholder: "Leave your message here?" , :style=> "resize:none" %>
                        </div>
                	</div>
            	</div>

            	<div class="col-md-12">
            		<%= f.submit "Send Message",  class: "fbtn btn-primary pull-right", id: "validate" %>
            	</div>
	        	</div>
	      <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <form>
      
      <iframe width="600" height="450" frameborder="0" style="border:0"  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA-YXdw3mpXcf6daGYSPSf72JVuFRuUrjE &q=Space+Needle,Seattle+WA" allowfullscreen></iframe>
      </form>
    </div>
 </div>

app/views/home/message.js.erb
$("#contact_form").html("<%= escape_javascript(render(:partial => 'contact_form')) %>");
alert(" Youe message has been Send")
window.location.href='<%= url_for(:action => :contact_us) %>'