config/routes.rb
Rails.application.routes.draw do
  # require 'sidekiq/web'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users 
  devise_for :users, :controllers => {:registrations => "users/registrations", sessions: "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  resources :gallery	
	 		
  root 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/about_us' => 'home#about_us'
  post '/message' => 'home#message'
  post '/import_image' => 'gallery#import_image'
  get '/get_image/:id', to: 'gallery#get_image', as: 'get_image'
  get '/gallery_count', to: 'gallery#gallery_count'


  
  # mount Sidekiq::Web => '/sidekiq'

end

app/models/gallery.rb
class Gallery < ApplicationRecord
	validates_uniqueness_of :name, :case_sensitive => false
	mount_uploader :gallery_image, GalleryUploader
	validates :name, :presence => {:message => 'cannot be blank, Task not saved'}
  validate :presence_of_url_field
	belongs_to :user , :touch => true
  attr_accessor :flash_notice

	require 'roo'

  
  def self.import(file,user)
    debugger
    response_hash = {}
    spreadsheet = open_file(file)
    header = spreadsheet.row(1)
    if  header.include?("name") and  header.include?("gallery_image")
      response_hash = {success: 0, failed: 0, failed_rows: []}
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        gallery = Gallery.new(user_id: user.id, name: row["name"], remote_gallery_image_url: row["gallery_image"])
        if gallery.save
          response_hash[:success] += 1
        else
          response_hash[:failed] += 1
          response_hash[:failed_rows].push({"#{i.to_s}": gallery.errors.full_messages})
        end
      end
      response_hash  
    else
      response_hash[:error_message] = "Header is mendatory to import file"
    end
    response_hash 
  end

	def self.open_file(file)
    case File.extname(file.path)
      when ".csv" then
        Roo::CSV.new(file.path,csv_options: {encoding: Encoding::UTF_8}, header: true)
      when ".xls" then
        Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then
        Roo::Excelx.new(file.path, nil, :ignore)
      else
        raise "Unknown file type: #{file.original_filename}"
    end
  end

  private

    def presence_of_url_field
      if gallery_image.blank? and remote_gallery_image_url.blank?
        errors.add(:gallery_image, "File has no Image_url")
      end
    end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	require 'roo'

	#before_action :authenticate_user!	
	
	before_action :get_galleries, only: [:destroy, :index,:create, :update ,:import_image]
	before_action :get_gallery, only: [:update, :edit, :destroy]

	def index	
		if request.format.json?
			respond_to do |format|
				if @galleries.present?
				 format.json { 
		        render json: { 
		          status: "Success",
		          message: "Successful",
		          data: {name: @galleries},
		          code: 200 
		        } 
		     }   
		    else
		    	format.json { render json: { status: "Failure", message: "No image found", code: 500 } }
		    end	   
		  end  
		end 
	end


	def create	
		if request.format.json?
			@gallery =   Gallery.new(name: params[:gallery][:name], remote_gallery_image_url: params[:gallery][:gallery_image], user_id: current_user)
		 	respond_to do |format| 
			 	 if @gallery.save
	        format.json { render json: { status: "Success", message: "Successful", code: 200 } }
			 	 else
	        format.json { render json: { status: "Failure", message: @gallery.errors.full_messages, code: 500 } }
			 	 end
			end 
		else
			@gallery =  Gallery.create(gallery_params)
		end		 
	end

	def edit
	
	end


	def update
	   @gallery.update(gallery_params)

	end
		


	def destroy	
	  @gallery.destroy
	  respond_to do |format|
      format.js { render :layout=>false }
    end
  end 

  def get_image
	 if params[:id].match(/\A\d+\z/i).blank? # means it does have some non numeric character
    message = "Image id can be numeric only"
    respond_to do |format|
      format.html { redirect_to gallery_index_path, notice: message }
      format.json { render json: { status: "Failure", message: message, code: 500 } }
    end
  else
    @gallery = Gallery.find_by_id(params[:id])

    respond_to do |format|
      if @gallery.present?
        format.html
        format.json { 
          render json: { 
            status: "Success",
            message: "Successful",
            data: {name: @gallery.name, url: request.protocol + request.host_with_port + @gallery.image_url},
            code: 200 
          } 
        }
      else
        format.html { redirect_to gallery_index_path, notice: "No image found" }
        format.json { render json: { status: "Failure", message: "No image found", code: 500 } }
      end
    end
  end
  	
  end


  def gallery_count
  	sleep(2);
  	@gallery_count =  current_user.galleries.size
  	respond_to do |format|
  		format.js
  	end	
  end



  def import_image
		response = Gallery.import(params[:file], current_user) 
 		unless response[:error_message].present?
			message_string = "#{response[:success]} files imported successfully.<br/>"
	    message_string += "#{response[:failed]} files failed to import."
	    if response[:failed] > 0
	      message_string += ""
	      response[:failed_rows].each do |row|
	        message_string += "Row Id: #{row.keys[0]} <br />"
	        row[row.keys[0]].each do |message|
	          message_string += message + "<br />"
	        end
	      end
	    end
	    flash[:notice] = message_string
    	redirect_to gallery_index_path
	  else
	  	@gallery = Gallery.new
      flash.now[:error] = response[:error_message]
      render :index
    end	
	end

	private 
	
	def get_gallery
		@gallery = Gallery.find(params[:id])
		
	end

	def get_galleries
		@user = current_user
		@galleries = current_user.galleries if current_user.galleries.present?
		@galleries= @galleries.order(:name).page(params[:page]).per(4) if @galleries.present?


	end

	def gallery_params
		params.require(:gallery).permit(:user_id , :name , :gallery_image)
	end

end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/_delete.html.erb
<div class="row">
	<% @galleries.each  do |gallery| %>
		<div class="col-xs-6 col-sm-4 col-md-3">            
		    <div class="thumbnail">
		        <div class="caption">
		             <h4><%= gallery.name  if gallery.name.present?  %></h4>	
		            <p>short thumbnail description</p>
		            <p><a href="" class="label label-danger">Edit</a> 
		            <%= link_to "Delete", gallery_path(gallery), method: 'delete', :class=> "label label-default",  confirm: "Are you sure?", remote: true, id: "delete_gallery" %></p>
		        </div>
		        <img src="<%= gallery.gallery_image_url(:thumb)%>" alt="...">
		    </div>
		</div>
	<% end %>  
</div>

app/views/gallery/_edit.html.erb
	<div id="myModal2" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Edit Image</h4>
				</div>
				<%= form_for (@gallery) , method: 'put', remote: true do |f| %>
					<div class="modal-body">
						<%= f.label :name  %><br />
						<%= f.text_field :name, autofocus: true, :class => "form-control", :placeholder => "Enter Image Name"%>
						<%= f.label :upload_image%><br />
						<%= f.file_field :gallery_image %>

					</div>
					<div class="modal-footer">
						<%= f.submit "Submit", :class => "btn btn-default", :input_html => {"data-dismiss" => "modal"}%>
					</div>
				<% end %> 
				</div>
			</div>
		</div>
	</div>

app/views/gallery/create.js.erb
<% if @gallery.errors.any? %>
	alert("<%= j @gallery.errors.full_messages.to_sentence %>")
<% else %>
	window.location.href='<%= url_for(:action => :index) %>'	
<% end%>	

app/views/gallery/destroy.js.erb
$("#gallery").html("<%= escape_javascript(render(:partial => 'delete')) %>");

app/views/gallery/edit.js.erb
$("#edit_gallery").html("<%= escape_javascript(render(:partial => 'edit', :locals => {:gallery_id => @gallery})) %>");
$('#myModal2').modal('show');

app/views/gallery/gallery_count.js.erb
$("#count").html("<%= @gallery_count %>");
$(".total-yellow").css("background-color", "green");
$(".loading").css("display","none");	

app/views/gallery/index.html.erb
<script async src='https://content.maropost.com/uploads/1/websites/7/e07f903c826cd1938d47b3806d195290895a38aa-v3.js' type='text/javascript'></script>
<div class="container" id="edit_gallery">
	<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal1">Upload Image</button>
	<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal3">Import Image</button>
	<div class="total-yellow">
		<b>Image Count</b>
		 <img class="loading" src="/assets/loader_icon.gif" >
		<b id="count"></b>

	</div>
		
	<div id="myModal1" class="modal fade" role="dialog">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Upload Image</h4>
	      </div>
	      <%= form_for :gallery , method: 'post', remote: true do |f| %>
		      <div class="modal-body">
		     		<%= f.label :name %><br />
		        <%= f.text_field :name, autofocus: true, :class => "form-control", :placeholder => "Enter Image Name"%>
		        <%= f.label :upload_image%><br />
		        <%= f.file_field :gallery_image %>
		         <%= f.hidden_field :user_id, :value => @user.id%>
		      </div>
		      <div class="modal-footer">
		      	<%= f.submit "Submit", :class => "btn btn-default", :input_html => {"data-dismiss" => "modal"}%>
		      </div>
		    <% end %> 
	    </div>

	  </div>
	</div>
	<div id="myModal3" class="modal fade" role="dialog">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Upload Image</h4>
	      </div>
				<%= form_tag import_image_path, multipart: true do %>
				  <div class="modal-body">
				  	<%= file_field_tag :file, accept: 'text/csv' %>
				  </div>	
		      <div class="modal-footer">
		      	<%= submit_tag "Submit", :class => "btn btn-info btn-lg", :input_html => {"data-dismiss" => "modal"}%>
		      </div>
	    	<% end %> 
	    </div>
	  </div>
	</div>

	<% if @galleries.present? %>
		<div class="container" id="gallery">  
			 <div class="row"></div>
			 <div class="err"></div>
				<% @galleries.each  do |gallery| %>
					<% cache(gallery, expires_in: 5.minutes) do %>
				    <div class="col-xs-6 col-sm-4 col-md-3">            
				        <div class="thumbnail">
				            <div class="caption">
				                <h4><%= gallery.name  if gallery.name.present?  %></h4>

				                <p><%= link_to 'Edit', edit_gallery_path(gallery), :class=> "label label-default", data: {toggle: "modal", target: "#myModal2"}, remote: true %>
				                <%= link_to "Delete", gallery_path(gallery), method: 'delete', :class=> "label label-default",  confirm: "Are you sure?", remote: true, id: "delete_gallery" %></p>
				            </div>
				            <img src="<%= gallery.gallery_image_url(:thumb)%>" alt="...">
				        </div>
				    </div>
				  <% end %>
				<% end %>    
			 </div> 
			 <%= link_to_prev_page @galleries, 'Previous Page', :class=> "label label-default" %>
			 <%= link_to_next_page @galleries, 'Next Page', :class=> "label label-default" %>
		</div>
	<% end %>

</div>






<style type="text/css">

.total-yellow {
	display: inline-block;
    margin-bottom: 0;
    font-weight: normal;
    text-align: center;
    vertical-align: middle;
    background-image: none;
    border: 5px solid transparent;
    white-space: nowrap;
    color: black;
    background-color: yellow;
    text-decoration: none;
}

	.footer-bottom {
    margin-top: 60%;
}

 .loading{
   	max-width: 32px;
  	max-height: 200px;
  }
</style>

<script type="text/javascript">
	$(document).on('turbolinks:load', function() {
		$.ajax({
	    type:'GET',
	    url:'/gallery_count',
	  });	
	});
</script>

app/views/gallery/update.js.erb
<% if @gallery.errors.any? %>
	alert("<%= j @gallery.errors.full_messages.to_sentence %>")
<% else %>
	$("#gallery").html("<%= escape_javascript(render(:partial => 'delete')) %>");
	$('#myModal2').modal('show');
	window.location.href='<%= url_for(:action => :index) %>'
	
<% end%>	