config/routes.rb
Rails.application.routes.draw do
  # require 'sidekiq/web'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users 
  devise_for :users, :controllers => {:registrations => "users/registrations", sessions: "users/sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  resources :gallery	
	 		
  root 'home#about_us'
  get '/contact_us' => 'home#contact_us'
  get '/about_us' => 'home#about_us'
  post '/message' => 'home#message'
  post '/import_image' => 'gallery#import_image'
  get '/get_image/:id', to: 'gallery#get_image', as: 'get_image'
  get '/gallery_count', to: 'gallery#gallery_count'


  
  # mount Sidekiq::Web => '/sidekiq'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async src='https://content.maropost.com/uploads/4/websites/345/e07f903c826cd1938d47b3806d195290895a38aa-v2.js' type='text/javascript'></script></head>
  <body>
  <% if user_signed_in?%>
  	<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">DemoProject</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav">
			        <li class="active"><%= link_to "About_us", about_us_path %></li>
			        <li class="active"><%= link_to "Contact_us", contact_us_path %></li>
			        <li class="active" id="gallery_count"><%= link_to "Gallery", gallery_index_path %></li>
		      </ul>
		      <ul class="nav navbar-nav navbar-right">
		      	<% unless user_signed_in? %>
			        <li><%= link_to "Sign up", new_registration_path(resource_name) , class: "glyphicon glyphicon-user" %> </li>
			        <li><%= link_to "Login" , new_session_path(resource_name), class: "glyphicon glyphicon-log-in active" %></li>
			    <% else %>
			    	<li class= "active"><%= link_to "Signout", destroy_user_session_path, method: "delete" %></li>
			    	<li class="active" ><%= link_to "Change password", edit_user_registration_path %></li>
			    <% end %>
		      </ul>
		    </div>
		  </div>
		</nav>
	<% end %>
	 <% flash.each do |key, value| %>
        <div><%= value.html_safe %></div>
    <% end %>
    <%= yield %>
    <% if user_signed_in?%>
	    <div class="footer-bottom">
				<div class="container">
					<div class="row">
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<div class="copyright">
								© 2017 Maropost Inc. All rights reserved. | <%= link_to "Contact Us", contact_us_path %>
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
  </body>
</html>